-- Query 1
-- Total MRR by customer segment
-- Business question: What is the total Monthly Recurring Revenue (MRR) generated by each customer segment?
-- Total MRR generated by each customer segment

SELECT
    segment,
    SUM(mrr) AS total_mrr
FROM customers
GROUP BY segment;




-- Query 2
-- Top 10 customers by MRR
-- Business question: Which customers generate the highest Monthly Recurring Revenue?

SELECT
    customer_id,
    company_name,
    segment,
    mrr
FROM customers
ORDER BY mrr DESC
LIMIT 10;




-- Query 3
-- Month-over-month MRR change
-- Business question: How does total monthly revenue change from one month to the next?

WITH monthly_revenue AS (

    SELECT
        month,
        SUM(amount) AS revenue
    FROM transactions
    GROUP BY month

)
SELECT
    month,
    revenue,
    revenue - LAG(revenue) OVER (ORDER BY month) AS mom_change
FROM monthly_revenue
ORDER BY month;




-- Query 4
-- Logo churn rate per month
-- Business question: How many customers churned in each month?

SELECT
    month,
    COUNT(DISTINCT customer_id) AS churned_customers
FROM transactions
WHERE transaction_type = 'churn'
GROUP BY month
ORDER BY month;




-- Query 5
-- Average CSAT by support channel
-- Business question: What is the average customer satisfaction score for each support channel?

SELECT
    channel,
    AVG(csat_score) AS average_csat
FROM support_tickets
GROUP BY channel
ORDER BY average_csat DESC;




-- Query 6
-- Support tickets per customer per month
-- Business question: How many support tickets does each customer create per month?

SELECT
    customer_id,
    strftime('%Y-%m', open_date) AS month,
    COUNT(ticket_id) AS ticket_count
FROM support_tickets
GROUP BY customer_id, month
ORDER BY month, ticket_count DESC;




-- Query 7
-- Cohort retention (3-month MRR retention)
-- Business question: What percentage of starting MRR remains active after three months for each signup cohort?
-- grouped by acquisition quarter?

WITH cohort AS (

SELECT
customer_id,
mrr,
strftime('%Y', acquisition_date) || '-Q' ||
((CAST(strftime('%m', acquisition_date) AS INTEGER)-1)/3 +1)
AS signup_quarter
FROM customers

)
SELECT
signup_quarter,
SUM(mrr) AS starting_mrr,
ROUND(100.0 * SUM(mrr) /
SUM(SUM(mrr)) OVER (),2) AS percent_of_total
FROM cohort
GROUP BY signup_quarter
ORDER BY signup_quarter;




--  Query 8
-- Customers who had more than 3 support tickets in a single month within 60 days before churning
-- Business question: Which customers had more than three support tickets in a single month within 60 days before churn?


WITH churned AS (

    SELECT
        customer_id,
        month AS churn_month
    FROM transactions
    WHERE transaction_type='churn'

),

ticket_counts AS (

    SELECT
        customer_id,
        strftime('%Y-%m', open_date) AS ticket_month,
        COUNT(*) AS ticket_count
    FROM support_tickets
    GROUP BY customer_id, ticket_month

)
SELECT
    t.customer_id,
    t.ticket_month,
    t.ticket_count
FROM ticket_counts t
JOIN churned c
ON t.customer_id = c.customer_id
WHERE t.ticket_count > 3
ORDER BY t.ticket_count DESC;









